# Generated by Django 2.2.6 on 2019-10-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='country',
        ),
        migrations.RemoveField(
            model_name='value',
            name='indicator',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='code',
            new_name='indicator_code',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='name',
            new_name='indicator_name',
        ),
        migrations.AddField(
            model_name='indicator',
            name='country_code',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='country_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='value',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='indicator',
            name='year',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
