# Generated by Django 2.2.6 on 2019-10-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191018_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='indicator_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='indicator_name',
            new_name='name',
        ),
    ]
